### ISSUE TITLE
Tasks randomly fail (FileUploadMiscError) when uploading to Blob Storage

### ISSUE THREAD

**Issue by lolochristen** [Azure/Batch#128]
#### Problem Description

Since a view weeks almost every job started to fail because one task (of several) fails (FileUploadMiscError) when uploading to Blob Storage (after successful processing). The jobs/tasks worked perfectly for almost half a year. Also, much bigger files have been processed in the passed and other tasks could upload to blob storage using the same config. Other tasks within the job do not fail and cause no issues using the same blob storage and configuration. The internal error is this aiohttp.client_exceptions.ClientResponseError: 400, message='XML specified is not syntactically valid.', which looks like blob storage returns not an XML which cannot get parsed. Any clue why this started to happens? Thanks for any help and hints.

#### Steps to Reproduce

A job with several tasks with automatic file down and uploading is configured to run on a batch account using a standard_d4_v3 nodes on  windowsserver 2012-r2-datacenter-smalldisk. (2012 required because of required libraries). Blob storage is accessed using user assigned identity.

Task config:
```json
{
  "id": "AudioPackToWav_49163ee2-8956-4687-8b54-86b4b5fffe2e",
  "jobId": "Media_783_20220511_150022",
  "odata.metadata": "https://batch123.westeurope.batch.azure.com/$metadata#tasks/@Element",
  "url": "https://batch123.westeurope.batch.azure.com/jobs/Media_783_20220511_150022/tasks/AudioPackToWav_49163ee2-8956-4687-8b54-86b4b5fffe2e",
  "eTag": "0x8DA335EF8EEDEDD",
  "creationTime": "2022-05-11T15:00:22.2693085Z",
  "lastModified": "2022-05-11T15:00:22.2693085Z",
  "state": "completed",
  "stateTransitionTime": "2022-05-11T15:00:24.975175Z",
  "previousState": "running",
  "previousStateTransitionTime": "2022-05-11T15:00:22.333156Z",
  "commandLine": "cmd /c %AZ_BATCH_APP_PACKAGE_sox#14.4.2%\\sox-14.4.2\\sox.exe −r 16k −e signed −b 16 −c 1 audio.raw audio.wav",
  "resourceFiles": [
    {
      "httpUrl": "https://sa123.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.raw",
      "filePath": "audio.raw"
    }
  ],
  "outputFiles": [
    {
      "filePattern": "audio.wav",
      "destination": {
        "container": {
          "containerUrl": "https://sa123.blob.core.windows.net/exammeetingmedia/",
          "path": "d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav"
        }
      },
      "uploadOptions": {
        "uploadCondition": "TaskSuccess"
      }
    }
  ],
  "applicationPackageReferences": [
    {
      "applicationId": "sox",
      "version": "14.4.2"
    }
  ],
  "userIdentity": {
    "autoUser": {
      "scope": "pool",
      "elevationLevel": "nonadmin"
    }
  },
  "constraints": {
    "maxWallClockTime": "P10675199DT2H48M5.4775807S",
    "retentionTime": "P7D",
    "maxTaskRetryCount": 0
  },
  "requiredSlots": 1,
  "executionInfo": {
    "startTime": "2022-05-11T15:00:22.380009Z",
    "endTime": "2022-05-11T15:00:24.975175Z",
    "exitCode": 0,
    "failureInfo": {
      "category": "ServerError",
      "code": "FileUploadMiscError",
      "message": "A miscellaneous error was encountered while uploading one of the output files",
      "details": [
        {
          "name": "FilePath",
          "value": "D:\\batch\\tasks\\workitems\\Media_783_20220511_150022\\job-1\\AudioPackToWav_49163ee2-8956-4687-8b54-86b4b5fffe2e\\wd\\audio.wav"
        },
        {
          "name": "FilePattern",
          "value": "audio.wav"
        },
        {
          "name": "FileDestination",
          "value": "https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/"
        }
      ]
    },
    "result": "failure",
    "retryCount": 0,
    "requeueCount": 0
  },
  "nodeInfo": {
    "affinityId": "TVM:tvmps_6a53120f6b71a6548d3bd69cb2f680f5f636d3105aefd2fd767801d5e209e8fc_d",
    "nodeUrl": "https://sa123.westeurope.batch.azure.com/pools/ExamBotPool/nodes/tvmps_6a53120f6b71a6548d3bd69cb2f680f5f636d3105aefd2fd767801d5e209e8fc_d",
    "poolId": "ExamBotPool",
    "nodeId": "tvmps_6a53120f6b71a6548d3bd69cb2f680f5f636d3105aefd2fd767801d5e209e8fc_d",
    "taskRootDirectory": "workitems\\Media_783_20220511_150022\\job-1\\AudioPackToWav_49163ee2-8956-4687-8b54-86b4b5fffe2e",
    "taskRootDirectoryUrl": "https://sa123.westeurope.batch.azure.com/pools/ExamBotPool/nodes/tvmps_6a53120f6b71a6548d3bd69cb2f680f5f636d3105aefd2fd767801d5e209e8fc_d/files/workitems/Media_783_20220511_150022/job-1/AudioPackToWav_49163ee2-8956-4687-8b54-86b4b5fffe2e"
  }
}
```
#### Expected Results

no errors!

#### Actual Results

Tasks Error:
Internal Error: aiohttp.client_exceptions.ClientResponseError: 400, message='XML specified is not syntactically valid'

#### Additional Logs
fileuploaderr.txt:
```
{"code": "InternalError", "user_error": false, "pattern": "audio.wav", "file": "D:\\batch\\tasks\\workitems\\Media_783_20220511_150022\\job-1\\AudioPackToWav_49163ee2-8956-4687-8b54-86b4b5fffe2e\\wd\\audio.wav", "destination": "https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/"}
```

fileuploadout.txt:
```
2022-05-11 14:39:34,896 System default encoding=utf-8, filesystem encoding=utf-8, default locale encoding=cp1252
System default encoding=utf-8, filesystem encoding=utf-8, default locale encoding=cp1252
2022-05-11 14:39:34,912 Resolved mappings: [[Resolved mapping - base_path: D:\batch\tasks\workitems\Media_783_20220511_143922\job-1\AudioPackToWav_c81e91d9-adda-4f07-929e-fc26fc81cc20\wd, full_pattern: D:\batch\tasks\workitems\Media_783_20220511_143922\job-1\AudioPackToWav_c81e91d9-adda-4f07-929e-fc26fc81cc20\wd\audio.wav, original_pattern: audio.wav,  destination: d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav]]
Resolved mappings: [[Resolved mapping - base_path: D:\batch\tasks\workitems\Media_783_20220511_143922\job-1\AudioPackToWav_c81e91d9-adda-4f07-929e-fc26fc81cc20\wd, full_pattern: D:\batch\tasks\workitems\Media_783_20220511_143922\job-1\AudioPackToWav_c81e91d9-adda-4f07-929e-fc26fc81cc20\wd\audio.wav, original_pattern: audio.wav,  destination: d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav]]
2022-05-11 14:39:34,912 Uploading all files matching pattern D:\batch\tasks\workitems\Media_783_20220511_143922\job-1\AudioPackToWav_c81e91d9-adda-4f07-929e-fc26fc81cc20\wd\audio.wav
Uploading all files matching pattern D:\batch\tasks\workitems\Media_783_20220511_143922\job-1\AudioPackToWav_c81e91d9-adda-4f07-929e-fc26fc81cc20\wd\audio.wav
HTTP Request <bound method ClientSession.put of <aiohttp.client.ClientSession object at 0x0000005C4F73D790>> resulted in Bad Client Response: {'method': 'PUT', 'cookies': <SimpleCookie: >, '_real_url': URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist'), '_url': URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist'), '_body': b'\xef\xbb\xbf<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidXmlDocument</Code><Message>XML specified is not syntactically valid.\nRequestId:3c77af37-801e-0060-0e44-656c5f000000\nTime:2022-05-11T14:39:36.2180152Z</Message><LineNumber>0</LineNumber><LinePosition>0</LinePosition><Reason /></Error>', '_writer': None, '_continue': None, '_closed': True, '_history': (), '_request_info': RequestInfo(url=URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist'), method='PUT', headers=<CIMultiDictProxy('Host': 'edupoolprodstoacnexambot.blob.core.windows.net', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.8.1', 'Content-Length': '211', 'Content-Type': 'application/octet-stream')>, real_url=URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist')), '_timer': <aiohttp.helpers.TimerNoop object at 0x0000005C4F75BBB0>, '_cache': {'headers': <CIMultiDictProxy('Content-Length': '294', 'Content-Type': 'application/xml', 'Server': 'Blob Service Version 1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '3c77af37-801e-0060-0e44-656c5f000000', 'Date': 'Wed, 11 May 2022 14:39:35 GMT')>, 'url': URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist')}, '_traces': [], '_loop': <ProactorEventLoop running=True closed=False debug=False>, '_session': None, '_protocol': <aiohttp.client_proto.ResponseHandler object at 0x0000005C51BE5640>, '_connection': None, 'version': HttpVersion(major=1, minor=1), 'status': 400, 'reason': 'XML specified is not syntactically valid.', '_headers': <CIMultiDictProxy('Content-Length': '294', 'Content-Type': 'application/xml', 'Server': 'Blob Service Version 1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '3c77af37-801e-0060-0e44-656c5f000000', 'Date': 'Wed, 11 May 2022 14:39:35 GMT')>, '_raw_headers': ((b'Content-Length', b'294'), (b'Content-Type', b'application/xml'), (b'Server', b'Blob Service Version 1.0 Microsoft-HTTPAPI/2.0'), (b'x-ms-request-id', b'3c77af37-801e-0060-0e44-656c5f000000'), (b'Date', b'Wed, 11 May 2022 14:39:35 GMT')), 'content': <StreamReader eof>}
HTTP ClientResponseError: {'request_info': RequestInfo(url=URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist'), method='PUT', headers=<CIMultiDictProxy('Host': 'edupoolprodstoacnexambot.blob.core.windows.net', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.8 aiohttp/3.8.1', 'Content-Length': '211', 'Content-Type': 'application/octet-stream')>, real_url=URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist')), 'status': 400, 'message': 'XML specified is not syntactically valid.', 'headers': <CIMultiDictProxy('Content-Length': '294', 'Content-Type': 'application/xml', 'Server': 'Blob Service Version 1.0 Microsoft-HTTPAPI/2.0', 'x-ms-request-id': '3c77af37-801e-0060-0e44-656c5f000000', 'Date': 'Wed, 11 May 2022 14:39:35 GMT')>, 'history': ()})
Traceback (most recent call last):
  File "common\util\retry.py", line 184, in retry_helper_async
  File "azurestorage\helper.py", line 847, in wrapper_func
  File "aiohttp\client_reqrep.py", line 1004, in raise_for_status
aiohttp.client_exceptions.ClientResponseError: 400, message='XML specified is not syntactically valid.', url=URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist')
Traceback (most recent call last):
  File "batchfileuploader.py", line 122, in main
  File "agent\fileupload\uploader.py", line 489, in run
  File "agent\fileupload\uploader.py", line 391, in push_file_list_to_storage
common.exceptions.AggregateException: file: D:\batch\tasks\workitems\Media_783_20220511_143922\job-1\AudioPackToWav_c81e91d9-adda-4f07-929e-fc26fc81cc20\wd\audio.wav from pattern: audio.wav to destination: https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/ hit error: Traceback (most recent call last):
  File "common\util\retry.py", line 184, in retry_helper_async
  File "azurestorage\helper.py", line 847, in wrapper_func
  File "aiohttp\client_reqrep.py", line 1004, in raise_for_status
aiohttp.client_exceptions.ClientResponseError: 400, message='XML specified is not syntactically valid.', url=URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "azurestorage\helper.py", line 1664, in upload_multiple_files_async
  File "azurestorage\helper.py", line 1619, in upload_blob_async
  File "azurestorage\helper.py", line 943, in _http_request_wrapper_async
  File "common\util\retry.py", line 190, in retry_helper_async
  File "azurestorage\helper.py", line 934, in handle_exception
azurestorage.helper.HTTPNonRetryableError: 400, message='XML specified is not syntactically valid.', url=URL('https://edupoolprodstoacnexambot.blob.core.windows.net/exammeetingmedia/d91f5e00-3850-4b82-9686-ec143ed1b5dd/audio.wav?comp=blocklist')
```

**Comment by jaypatel-37** [comment]
Thanks for providing so much info! Issue was a code bug which has been fixed and is pending release. I'll update here again once the fix has been released.

**Comment by damienbod** [comment]
@jaypatel-37 Thanks for this feedback. Is there a workaround for this until the fix is released?

**Comment by lolochristen** [comment]
@jaypatel-37 Thanks for your input. We could successfully switch to SAS Keys to upload Files for the moment and jobs are running again. Where and how do you communicate known issues like this so we can avoid operative issues (from our perspective) in the future?

**Comment by jaypatel-37** [comment]
@lolochristen @damienbod The fix has been released. We usually don't communicate known issues other than tagging questions here as "known issue." If we do start posting known issues though it would likely be here on Github

**Comment by staer** [comment]
closing as the issue has been resolved and released
