### ISSUE TITLE
Tasks started failing (FileUploadMiscError) when uploading output files to Blob Storage

### ISSUE THREAD

**Issue by prashantsengar-cl** [Azure/Batch#171]
#### Problem Description

- Support requests should be raised from within the Azure Portal and not
through GitHub.
- All sensitive information should be redacted if filing an issue on GitHub.

#### Steps to Reproduce

I am using Python SDK to create Batch task that needs to upload output files to a storage container.

My Batch account Node Pool has been assigned a user-assigned managed identity which has the "Storage Blob Data Contributor" role to the storage container's storage account.

Here is a minimal reproducible of what I am doing:

```python

import os

from azure.batch import BatchServiceClient
from azure.batch import models as batchmodels
from azure.batch.batch_auth import SharedKeyCredentials
from azure.batch.models import (BatchErrorException,
                                ComputeNodeIdentityReference, OutputFile,
                                OutputFileBlobContainerDestination,
                                OutputFileDestination,
                                OutputFileUploadCondition,
                                OutputFileUploadOptions, TaskState)
from azure.identity import DefaultAzureCredential
from azure.keyvault.secrets import SecretClient


def create_batch_task(
    batch_client: BatchServiceClient, job_id: str, task_id: str, command: str
):
    # uploading log files to Azure Blob Storage
    # https://learn.microsoft.com/en-us/azure/batch/batch-task-output-files
    LOGS_CONTAINER_URL = os.environ.get("LOGS_CONTAINER_URL")  # https://STORAGE_ACCOUNT.blob.core.windows.net/batch-logs
    NODE_IDENTITY_RESOURCE_ID = os.environ.get("NODE_IDENTITY_RESOURCE_ID")  # /subscriptions/SUB_ID/resourcegroups/rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/MI_NAME
    destination = OutputFileDestination(
        container=OutputFileBlobContainerDestination(container_url=LOGS_CONTAINER_URL),
        path=f"{job_id}/{task_id}",
        identity_reference=ComputeNodeIdentityReference(
            resource_id=NODE_IDENTITY_RESOURCE_ID
        ),
    )
    upload_options = OutputFileUploadOptions(
        upload_condition=OutputFileUploadCondition.task_completion
    )
    # output files are stored in CWD's parent directory
    stdout = OutputFile(
        file_pattern="../stdout.txt",
        destination=destination,
        upload_options=upload_options,
    )
    stderr = OutputFile(
        file_pattern="../stderr.txt",
        destination=destination,
        upload_options=upload_options,
    )
    task = batchmodels.TaskAddParameter(
        id=task_id, command_line=command, output_files=[stdout, stderr]
    )
    batch_client.task.add(job_id, task)


batch_account_key = "ACCESS KEY"
region = "batch account region"
batch_account_url_format = "https://{BATCH_ACCOUNT_NAME}.{REGION}.batch.azure.com"
creds = SharedKeyCredentials(batch_account_name, batch_account_key)
batch_account_url = batch_account_url_format.format(
    BATCH_ACCOUNT_NAME=batch_account_name, REGION=region
)
batch_client = BatchServiceClient(creds, batch_url=batch_account_url)

create_batch_task(batch_client, "job-id", "task-id")

```

#### Expected Results

The task gets completed and the `stdout.txt` and `stderr.txt` file to get uploaded to the given storage container.

#### Actual Results

The task gets completed but the file upload fails.

fileuploadout.txt
```
2024-05-07 06:30:31,281 System default encoding=utf-8, filesystem encoding=utf-8, default locale encoding=UTF-8
System default encoding=utf-8, filesystem encoding=utf-8, default locale encoding=UTF-8
2024-05-07 06:30:31,373 Resolved mappings: [[Resolved mapping - base_path: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e, full_pattern: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e/stdout.txt, original_pattern: ../stdout.txt,  destination: None, Resolved mapping - base_path: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e, full_pattern: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e/stderr.txt, original_pattern: ../stderr.txt,  destination: None]]
Resolved mappings: [[Resolved mapping - base_path: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e, full_pattern: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e/stdout.txt, original_pattern: ../stdout.txt,  destination: None, Resolved mapping - base_path: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e, full_pattern: /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e/stderr.txt, original_pattern: ../stderr.txt,  destination: None]]
2024-05-07 06:30:31,373 Uploading all files matching pattern /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e/stdout.txt
Uploading all files matching pattern /mnt/batch/tasks/workitems/BATCH_ACCOUNT_NAME/job-1/a18d4637-2322-43e2-9aca-e23c1324502e/stdout.txt
Traceback (most recent call last):
  File "batchfileuploader.py", line 122, in main
  File "agent/fileupload/uploader.py", line 489, in run
  File "agent/fileupload/uploader.py", line 366, in push_file_list_to_storage
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "azurestorage/helper.py", line 1758, in upload_multiple_files_async
  File "common/util/general.py", line 63, in ensure_param_not_none
ValueError: auth paramname or None param is None
```

fileuploaderr.txt
```
{"code": "UnknownError", "user_error": false, "pattern": null, "file": null, "destination": null}
```

#### Additional Logs

Task properties JSON

```json
{
    "id": "d28cfdccedd048dfbd00da11bb492ca4",
    "url": "https://BATCH_ACCOUNT_NAME.centralindia.batch.azure.com/jobs/BATCH_ACCOUNT_NAME/tasks/d28cfdccedd048dfbd00da11bb492ca4",
    "eTag": "0x8DC6E965DC9848E",
    "lastModified": "2024-05-07T13:05:27.740Z",
    "creationTime": "2024-05-07T13:05:27.740Z",
    "state": "completed",
    "stateTransitionTime": "2024-05-07T13:16:14.566Z",
    "previousState": "running",
    "previousStateTransitionTime": "2024-05-07T13:05:36.872Z",
    "commandLine": "/bin/bash -c 'echo hello'",
    "outputFiles": [
        {
            "filePattern": "../stdout.txt",
            "destination": {
                "container": {
                    "containerUrl": "https://STORAGE_ACCOUNT.blob.core.windows.net/batch-logs"
                }
            },
            "uploadOptions": {
                "uploadCondition": "TaskCompletion"
            }
        },
        {
            "filePattern": "../stderr.txt",
            "destination": {
                "container": {
                    "containerUrl": "https://STORAGE_ACCOUNT.blob.core.windows.net/batch-logs"
                }
            },
            "uploadOptions": {
                "uploadCondition": "TaskCompletion"
            }
        }
    ],
    "constraints": {
        "maxWallClockTime": "P10675199DT2H48M5.4775807S",
        "retentionTime": "P7D",
        "maxTaskRetryCount": 0
    },
    "requiredSlots": 1,
    "userIdentity": {
        "autoUser": {
            "scope": "pool",
            "elevationLevel": "nonadmin"
        }
    },
    "executionInfo": {
        "startTime": "2024-05-07T13:05:36.900Z",
        "endTime": "2024-05-07T13:16:14.566Z",
        "exitCode": 2,
        "failureInfo": {
            "category": "ServerError",
            "code": "FileUploadMiscError",
            "message": "A miscellaneous error was encountered while uploading one of the output files",
            "details": [
                {
                    "name": "AdditionalErrorCode",
                    "value": "FailureExitCode"
                }
            ]
        },
        "retryCount": 0,
        "requeueCount": 0,
        "result": "failure"
    },
    "nodeInfo": {
        "affinityId": "TVM:tvmps_08fd74edf9763da3dfe7f704da503580e915e873fd314244a079d000c24a7a73_d",
        "nodeUrl": "https://BATCH_ACCOUNT_NAME.centralindia.batch.azure.com/pools/small/nodes/tvmps_08fd74edf9763da3dfe7f704da503580e915e873fd314244a079d000c24a7a73_d",
        "poolId": "small",
        "nodeId": "tvmps_08fd74edf9763da3dfe7f704da503580e915e873fd314244a079d000c24a7a73_d",
        "taskRootDirectory": "workitems/BATCH_ACCOUNT_NAME/job-1/d28cfdccedd048dfbd00da11bb492ca4",
        "taskRootDirectoryUrl": "https://BATCH_ACCOUNT_NAME.centralindia.batch.azure.com/pools/small/nodes/tvmps_08fd74edf9763da3dfe7f704da503580e915e873fd314244a079d000c24a7a73_d/files/workitems/BATCH_ACCOUNT_NAME/job-1/d28cfdccedd048dfbd00da11bb492ca4"
    }
}
```

#### Additonal Comments

The code was working perfectly fine a couple of weeks ago. I do not remember changing anything on this.
Azure Batch SDK version: 14.1.0
Python Version: 3.10
```[tasklist]
### Tasks
```

**Comment by prashantsengar-cl** [comment]
This got fixed after updating to the latest SDK versions
