### ISSUE TITLE
Task error while running in a container supported pool

### ISSUE THREAD

**Issue by fertinaz** [Azure/Batch#86]
I'm trying to create an automated pipeline to send my HPC jobs using Azure Batch Service. 

These are the crucial parts for my current work-flow:

1. Login to my batch account:
```
az configure --defaults group=$RESOURCE_NAME location=$GEO
az batch account login --name $BATCH_ACCOUNT --shared-key-auth
az acr login --name mycontainerreg.azurecr.io 
```

2. Create a pool:
```
az batch pool create  --json-file pool.json 
```
using the following json file:
```
{
    "id": "mypool",
    "displayName": "mypool",
    "vmSize": "Standard_A1_v2",
    "virtualMachineConfiguration": {
        "imageReference": {
            "publisher": "microsoft-azure-batch",
            "offer": "ubuntu-server-container",
            "sku": "16-04-lts",
            "version": "latest"
        },
        "nodeAgentSKUId": "batch.node.ubuntu 16.04",
        "containerConfiguration": {
            "type": "DockerCompatible"
        }
    },
    "resizeTimeout": "PT15M",
    "targetDedicatedNodes": 1,
    "targetLowPriorityNodes": 0,
    "enableAutoScale": false,
    "enableInterNodeCommunication": false,
    "maxTasksPerNode": 1,
    "taskSchedulingPolicy": {
        "nodeFillType": "Pack"
    }
}
```

Note that I'm using `"offer": "ubuntu-server-container"` and `"containerConfiguration": { "type": "DockerCompatible" }` is enabled.

3. Create a job: very straightforward
```
az batch job create --id $JOB_NAME --pool-id $POOL_NAME
```

4. Create a task:
```
az batch task create --job-id $JOB_NAME  --json-file task.json 
```
where task.json is:
```
{
    "id": "mytask",
    "commandLine": "/bin/bash -c 'docker pull mycontainerreg.azurecr.io/hello-world:v1 && docker run mycontainerreg.azurecr.io/hello-world:v1'",
    "constraints": {
      "retentionTime": "P7D",
      "maxTaskRetryCount": 5
    },
    "containerSettings": {
      "containerRunOptions": "-rm",
      "imageName": "hello-world:v1",
      "registry":  "mycontainerreg.azurecr.io"
    },
    "userIdentity": {
      "autoUser": {
        "scope": "pool",
        "elevationLevel": "nonadmin"
      }
    },
    "nodeInfo": {
      "poolId": "mypool"
    }
}
```

## Expected Behavior

My expectation is to execute the following commands inside the pool called `mypool`:
```
docker pull mycontainerreg.azurecr.io/hello-world:v1
docker run mycontainerreg.azurecr.io/hello-world:v1
```

However, I receive an error instead:
```
attempting to read file task.json as utf-8-sig
msrest.exceptions : Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
cli.azure.cli.core.util : The command failed with an unexpected error. Here is the traceback:

The command failed with an unexpected error. Here is the traceback:

cli.azure.cli.core.util : object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 631, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 686, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/batch/_exception_handler.py", line 30, in batch_exception_handler
    reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 665, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 574, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/batch/custom.py", line 353, in create_task
    for i in range(0, len(tasks), MAX_TASKS_PER_REQUEST):
TypeError: object of type 'NoneType' has no len()
object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 631, in execute
    raise ex
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 686, in _run_job
    cmd_copy.exception_handler(ex)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/batch/_exception_handler.py", line 30, in batch_exception_handler
    reraise(*sys.exc_info())
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 665, in _run_job
    result = cmd_copy(params)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/commands/__init__.py", line 324, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/core/__init__.py", line 574, in default_command_handler
    return op(**command_args)
  File "/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/batch/custom.py", line 353, in create_task
    for i in range(0, len(tasks), MAX_TASKS_PER_REQUEST):
TypeError: object of type 'NoneType' has no len()
```

Please especially focus on the bottom line:  `TypeError: object of type 'NoneType' has no len()`.

I checked the source in `/usr/local/Cellar/azure-cli/2.4.0/libexec/lib/python3.8/site-packages/azure/cli/command_modules/batch/custom.py`. I guess error boils down to this chunk of code:
```
     if task is not None:
         client.add(job_id=job_id, task=task)
         return client.get(job_id=job_id, task_id=task.id)
 
     submitted_tasks = []
     for i in range(0, len(tasks), MAX_TASKS_PER_REQUEST):
         submission = client.add_collection(
             job_id=job_id,
             value=tasks[i:i + MAX_TASKS_PER_REQUEST])
         submitted_tasks.extend(submission.value)  # pylint: disable=no-member
     return submitted_tasks
```

An error occurs during the task creation, then the for loop fails with `has no len()` error. 

So, I have a few questions:

1. What is the problem in the task.json file? Is it this part:
```
    "containerSettings": {
      "containerRunOptions": "-rm",
      "imageName": "hello-world:v1",
      "registry":  "mycontainerreg.azurecr.io"
    },
```

If it is, what would be the correct syntax?

2. Could we have a more user-friendly error message?

3. Do you have a suggestion for the general rationale in this work-flow? Is there a better approach to handle this type of executions (sending HPC jobs from local)?

Thank you

## Environment Summary
```
macOS-10.15.3-x86_64-i386-64bit
Python 3.8.2
Installer: HOMEBREW

azure-cli 2.4.0 *

```

**Comment by alfpark** [comment]
Tagging @bgklein.

**Comment by fertinaz** [comment]
I've fixed the problem by following these steps:

1. Added my user account in the IAM service as the owner in the Azure Container Registry
2. Removed `docker pull && docker run` from the `commandLine` in `task.json` because according to the documentation: *Batch automatically creates the container, the command line only specifies the command or commands that will run in the container.* 

Ref: https://docs.microsoft.com/en-us/azure/batch/batch-docker-container-workloads

Now, I can successfully run the hello-world container by executing the shell script on my local.

So now that my main problem is resolved you can close this issue. However, I'd appreciate if you have suggestions regarding the 3rd one. Thank you

**Comment by alfpark** [comment]
Submitting jobs to the Batch service is dependent upon your workflow. Using the CLI is completely fine if it falls within your use case. Using any of the provided SDKs may prove to be a better option if you want to tie your submission implementation programmatically with Batch.
