### ISSUE TITLE
Batch connecting to Azure Key Vault in a pool using a managed Identity

### ISSUE THREAD

**Issue by JSpenced** [Azure/Batch#97]
#### Problem Description

I am trying to use a pool in Azure Batch to connect to an Azure Key Vault. I have found some code online, but I didn't know if this is possible or the certificate root is the only possibility. I have enabled a managed identity for the batch account and added it to the keyvault. But when I try to get the managed Identitry from the python sdk in a batch pool then it fails.

The outline would be this code where DefaultAzureCredential when it comes to ManagedIdentityCredential fails. Any suggestions if this is possible to work from a batch pool when enabling managed identities in Azure batch.

```
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential

    KVUri = f"https://{keyVaultName}.vault.azure.net"

    credential = DefaultAzureCredential()
    client = SecretClient(vault_url=KVUri, credential=credential)

    secretName = "secret"
    retrieved_secret = client.get_secret(secretName)
    print(retrieved_secret)
```

#### Steps to Reproduce

1. Create batch account with managed identity.
2. Create batch pool and make sure has python sdk installed.
3. Will need to `pip install azure-keyvault azure-identity`
4. Make sure to add the managed identity to the key-vault with the get and list attributes for secrets.
5. Run the above code in a batch filling in necessary variables.

#### Expected Results

The above has access to the key vault from the batch pool.

#### Actual Results
Throws this error:
```
retrieved_secret = client.get_secret(secretName)
EnvironmentCredential.get_token failed: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ManagedIdentityCredential.get_token failed: ManagedIdentityCredential authentication unavailable. No identity has been assigned to this resource.
libsecret did not perform properly.
* If you encountered error "Remote error from secret service:
  org.freedesktop.DBus.Error.ServiceUnknown",
  you may need to install gnome-keyring package.
* Headless mode (such as in an ssh session) is not supported.
Traceback (most recent call last):
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/msal_extensions/libsecret.py", line 126, in trial_run
    agent.save(payload)  # It would fail when running inside an SSH session
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/msal_extensions/libsecret.py", line 103, in save
    data, None)
GLib.GError: g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)
libsecret did not perform properly.
* If you encountered error "Remote error from secret service:
  org.freedesktop.DBus.Error.ServiceUnknown",
  you may need to install gnome-keyring package.
* Headless mode (such as in an ssh session) is not supported.

SharedTokenCacheCredential.get_token failed: Shared token cache unavailable
VisualStudioCodeCredential.get_token failed: Failed to get Azure user details from Visual Studio Code.
AzureCliCredential.get_token failed: Please run 'az login' to set up an account
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. No identity has been assigned to this resource.
	SharedTokenCacheCredential: Shared token cache unavailable
	VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
	AzureCliCredential: Please run 'az login' to set up an account
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/azure/keyvault/secrets/_client.py", line 72, in get_secret
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/azure/keyvault/secrets/_generated/_operations_mixin.py", line 1475, in get_secret
    return mixin_instance.get_secret(vault_base_url, secret_name, secret_version, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/azure/keyvault/secrets/_generated/v7_1/operations/_key_vault_client_operations.py", line 276, in get_secret
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/core/pipeline/_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/core/pipeline/policies/_redirect.py", line 157, in send
    response = self.next.send(request)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/core/pipeline/policies/_retry.py", line 436, in send
    response = self.next.send(request)
  File "/usr/local/lib/python3.6/dist-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 111, in send
    self._handle_challenge(request, challenge)
  File "/usr/local/lib/python3.6/dist-packages/azure/keyvault/secrets/_shared/challenge_auth_policy.py", line 137, in _handle_challenge
    self._token = self._credential.get_token(scope)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/identity/_credentials/default.py", line 140, in get_token
    return super(DefaultAzureCredential, self).get_token(*scopes, **kwargs)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/azure/identity/_credentials/chained.py", line 90, in get_token
    raise ClientAuthenticationError(message=message)
azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
	ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. No identity has been assigned to this resource.
	SharedTokenCacheCredential: Shared token cache unavailable
	VisualStudioCodeCredential: Failed to get Azure user details from Visual Studio Code.
	AzureCliCredential: Please run 'az login' to set up an account
>>> ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. No identity has been assigned to this resource.
  File "<stdin>", line 1
    ManagedIdentityCredential: ManagedIdentityCredential authentication unavailable. No identity has been assigned to this resource.
                                                                      ^
SyntaxError: invalid syntax
>>> from msrestazure.azure_active_directory import MSIAuthentication
>>>
>>> credentials = MSIAuthentication(resource='https://login.microsoftonline.com/f1177991-5c8e-4cb7-af93-c51ad5bede11')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 600, in set_token
    token_entry = self._vm_msi.get_token(self.resource)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 649, in get_token
    token_entry = self._retrieve_token_from_imds_with_retry(resource)
  File "/home/zjhrdq/.local/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 704, in _retrieve_token_from_imds_with_retry
    raise HTTPError(request=result.request, response=result.raw)
requests.exceptions.HTTPError
>>> credential = credential = DefaultAzureCredential('https://login.microsoftonline.com/f1177991-5c8e-4cb7-af93-c51ad5bede11')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
>>> credential = DefaultAzureCredential('https://login.microsoftonline.com/f1177991-5c8e-4cb7-af93-c51ad5bede11')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
```
#### Additional Logs
```
INSERT ADDITIONAL LOGS HERE
```

**Comment by alfpark** [comment]
This was asked/answered here: https://stackoverflow.com/questions/63965005/using-managed-identity-in-azure-batch-to-authenticate-with-key-vault-using-pytho
