### ISSUE TITLE
Error on basic pool creation using batch

### ISSUE THREAD

**Issue by fertinaz** [Azure/Batch#98]
#### Problem Description

My existing C# code which used to work successfully before now fails with the following error:
```
Unhandled exception. System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.Batch.Protocol.JobOperations.AddWithHttpMessagesAsync(JobAddParameter job, JobAddOptions jobAddOptions, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.ExecuteRequestWithCancellationAsync(Func`2 func)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.ExecuteRequestAsync()
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.ExecuteRequestAsync()
   at Microsoft.Azure.Batch.ProtocolLayer.ProcessAndExecuteBatchRequest[TResponse](IBatchRequest`1 request, BehaviorManager bhMgr)
   at Microsoft.Azure.Batch.CloudJob.CommitAsync(IEnumerable`1 additionalBehaviors, CancellationToken cancellationToken)
   at Microsoft.Azure.Batch.UtilitiesInternal.WaitAndUnaggregateException(Task task)
   at Microsoft.Azure.Batch.UtilitiesInternal.WaitAndUnaggregateException(Task task, IEnumerable`1 rootBehaviors, IEnumerable`1 additionalBehaviors)
   at Microsoft.Azure.Batch.CloudJob.Commit(IEnumerable`1 additionalBehaviors)
   at hpcaascli.Program.RunSubmitAndReturnExitCode(SubmitOptions opts) in /fullpathtomycode/Program.cs:line 107
   at hpcaascli.Program.<>c.<Main>b__0_0(SubmitOptions opts) in /fullpathtomycode/Program.cs:line 17
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at hpcaascli.Program.Main(String[] args) in /fullpathtomycode/Program.cs:line 18
```

#### Steps to Reproduce
I've written this piece of code based on the sample provided here: 
https://github.com/Azure-Samples/batch-dotnet-quickstart

Here is what I'm doing step by step:
* Get Azure Batch credentials
```
BatchSharedKeyCredentials cred = new BatchSharedKeyCredentials(
                batchAccount.Url,
                batchAccount.Name,
                batchAccount.Key);
```

Following operations are inside the block `using (BatchClient batchClient = BatchClient.Open(cred))`

* Configure VM pool
```
        public void CreatePool(BatchClient batchClient, Job myJob)
        {
            var imageReference = CreateImageReference();
            var vmConfiguration = CreateVirtualMachineConfiguration(imageReference);

            CreateBatchPool(batchClient, vmConfiguration, PoolName, myJob.Nodes);
        }

        private static ImageReference CreateImageReference()
        {
            return new ImageReference(
                publisher: "microsoft-azure-batch",
                offer: "centos-container",
                sku: "7-7");
        }

        private static VirtualMachineConfiguration CreateVirtualMachineConfiguration(
            ImageReference imageReference)
        {
            return new VirtualMachineConfiguration(
                imageReference: imageReference,
                nodeAgentSkuId: "batch.node.centos 7");
        }
```

* Create pool
```
            try
            {
                string PoolVMSize = "Standard_A1_v2";

                CloudPool pool = batchClient.PoolOperations.CreatePool(
                    poolId: PoolId,
                    targetDedicatedComputeNodes: PoolNodeCount,
                    virtualMachineSize: PoolVMSize,
                    virtualMachineConfiguration: vmConfiguration);

                pool.Commit();  
            }
```

#### Expected Results

A VM pool should be created successfully.

#### Actual Results

See error above.

#### Additional Logs
OS: 19.6.0 Darwin
Batch: 13.0.0

Let me know if you need any additional information.

**Comment by fertinaz** [comment]
Looks like the order of the constructor arguments of the ImageReference class has changed. 

See code snippet from the sample I've shared above - https://github.com/Azure-Samples/batch-dotnet-quickstart/blob/474d60f7c79c2bba15ab9ee29e68786bd58701c3/BatchDotnetQuickstart/Program.cs#L240
```
        private static ImageReference CreateImageReference()
        {
            return new ImageReference(
                publisher: "MicrosoftWindowsServer",
                offer: "WindowsServer",
                sku: "2016-datacenter-smalldisk",
                version: "latest");
        }
```

Current function declaration looks like this:
```
public ImageReference (string offer, string publisher, string sku, string version = null);
```

I don't know why, but apparently offer and publisher is swapped. Fixing code based on this information resolves the issue.

Closing
